- name: install nginx service
  dnf:
    name: nginx
    state: present

- name: ensure nginx service is enabled and running
  service: 
    name: nginx 
    state: started 
    enabled: yes

- name: allow http service
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: firewalld reload
  command: firewall-cmd --reload