- name: find prometheus binary
  command: "find /opt/prometheus/ -type f -name prometheus"
  register: prometheusbin

- name: find prometheus config
  command: "find /opt/prometheus/ -type f -name prometheus.yml"
  register: prometheusconfig

- debug: msg="{{prometheusbin.stdout}}"

- debug: msg="{{prometheusconfig.stdout}}"

- set_fact:
    prometheusbin: "{{ prometheusbin.stdout }}"

- set_fact:
    prometheusconfig: "{{ prometheusconfig.stdout }}"

- name: "ensure prometheus service started"
#  command: "/opt/prometheus/prometheus-2.49.0-rc.1.linux-amd64/prometheus --config.file=/opt/prometheus/prometheus-2.49.0-rc.1.linux-amd64/prometheus.yml --web.listen-address=':2121'"
  shell: "{{prometheusbin}} --config.file={{prometheusconfig}} --web.listen-address=':2121' 2>&1 &"
