- name: import elasticsearch gpg key
  shell: rpm --import "{{ elasticsearch_gpg_key }}"

- name: configure elasticsearch repository
  copy:
    src: "elasticsearch.repo"
    dest: /etc/yum/repos.d/

- name: enable elasticsearch repository
  shell: dnf config-manager --set-enabled elasticsearch

- name: ensure elasticsearch installed
  dnf:
    name: elasticsearch
    state: present

- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: ensure elasticsearch service is running
  service:
    name: elasticsearch
    state: started