---
- name: Connect to default database and create a user with super prvileges
  become: true
  become_user: admin
  postgresql_user:
    name: '{{ postgres_user }}'
    password: '{{ postgres_user_password }}'
    role_attr_flags: CREATEDB,SUPERUSER,CREATEROLE,LOGIN

- name: Create a new database with name "pgdatabase"
  become: true
  become_user: admin
  postgresql_db:
    login_host: '{{ postgres_db_host }}'
    login_user: '{{ postgres_user }}'
    login_password: '{{  postgres_user_password }}'
    port: '{{ postgres_port }}'
    name: '{{ postgres_db_name }}'
