- name: install pip
  dnf:
    name: python3-pip
    state: present
  
- name: ensure flask pre-requisite installed
  command: pip install Flask

- name: deploy flask application
  copy:
    src: "{{ flask_apps_root }}"
    dest: "{{ flask_deploy_root }}"

- name: start flask application
  shell: cd "{{ flask_deploy_root }}/flaskapps" ; nohup flask --app backend run --host=fedresearch.stack.com --port=2121 2>&1 &

- name: start flask application
  shell: cd "{{ flask_deploy_root }}/flaskapps" ; nohup flask --app backend run --host=fedresearch.stack.com --port=2122 2>&1 &