# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
  
    config.vm.define "gitlab" do |gitlab|
      gitlab.vm.box = "fedora/38-cloud-base"
      gitlab.vm.hostname = "fedgitlab.stack.com"
  
      gitlab.vm.synced_folder '.', '/vagrant', disabled: true
      gitlab.vm.synced_folder ".", "/home/vagrant/gitlab", type: "sshfs"
  
      gitlab.vm.provider "libvirt" do |libvirt|
        libvirt.cpus = 2
        libvirt.memory = 4096
      end
  
      # Switch to "ansible_local" to install and use ansible on guest VM
  
      gitlab.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/linux_provision_gitlab_server.yml"
        ansible.verbose = true
      end
    end
  end
