- name: ensure backup directory present
  file: 
    path: "{{ nfs_config_backup }}"
    state: directory
    mode: '0755'

- name: ensure nfs config backup
  shell: cp -pr "{{ nfs_config }}" "{{ nfs_config_backup }}"/exports_$(date +%F_%H_%M_%Z)
