# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  config.vm.define "trivy" do |trivy|
    trivy.vm.box = "fedora/38-cloud-base"
    trivy.vm.hostname = "fedtrivy.stack.com"

    trivy.vm.synced_folder '.', '/vagrant', disabled: true
    trivy.vm.synced_folder ".", "/home/vagrant/trivy", type: "sshfs"

    trivy.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
    end

    # Switch to "ansible_local" to install and use ansible on guest VM

    trivy.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/linux_provision_trivy_server.yml"
      ansible.verbose = true
    end
  end
end
