---
- name: ensure aws client home directory exists
  file:
    path: "{{aws_client_home}}"
    state: directory
    owner: "{{aws_client_user}}"
    group: "{{aws_client_group}}"
    mode: 0755

- name: upload aws config
  copy:
    src: "{{aws_client_home}}/config.template"
    dest: "{{aws_client_home}}/config"
    owner: "{{aws_client_user}}"
    group: "{{aws_client_group}}"
    mode: '0600'

- name: upload aws credentials
  copy:
    src: "{{aws_client_home}}/credentials.template"
    dest: "{{aws_client_home}}/credentials"
    owner: "{{aws_client_user}}"
    group: "{{aws_client_group}}"
    mode: "0600"
