- name: ensure cronjob script directory exists
  file:
    name: "{{ cronjob_scripts_loc }}"
    state: directory
    owner: admin
    group: admin
    mode: '0755'

- name: copy cronjob execution script
  copy:
    src: passwordexpirynotify.sh
    dest: "{{ cronjob_scripts_loc }}"
    owner: admin
    group: admin
    mode: '0755'

#- name: create crontab entry for root user
#  cron:
#    name: password expiry notification
#    minute: "0"
#    hour: "5"
#    job: "{{ cronjob_scripts_loc }}/passwordexpirynotify.sh {{ user }} > /dev/null 2>&1"

- name: create crontab entry for admin user
  cron:
    name: password expiry notification
    minute: "0"
    hour: "5"
    user: "admin"
    job: "{{ cronjob_scripts_loc }}/passwordexpirynotify.sh {{ user }} > /dev/null 2>&1"
