- name: get the current crypto policy applied to system
  shell: update-crypto-policies --show
  register: cryptopolicy_output

- name: print current crypto policy applied to system
  debug: msg="{{ cryptopolicy_output.stdout }}"