# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "fedora/38-cloud-base"
    nginx.vm.hostname = "fednginx.stack.com"
    nginx.vm.network "forwarded_port", guest: 80, host: 8080

    nginx.vm.synced_folder '.', '/vagrant', disabled: true
    nginx.vm.synced_folder ".", "/home/vagrant/nginx", type: "sshfs"

    nginx.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048
    end

    # Switch to "ansible_local" to install and use ansible on guest VM

    nginx.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/linux_provision_nginx_server.yml"
      ansible.verbose = true
    end
  end
end
