---
- name: downaload and extract cilium
  unarchive:
    src: "{{cilium_repo}}"
    dest: /usr/local/bin
    remote_src: yes

#- name: install cilium
#  become: true
#  become_user: admin
#  command: "/usr/local/bin/cilium install"
#  register: kubernetes_cilium_install
#
#- name: print the cilium install status
#  debug:
#    msg: "{{ kubernetes_cilium_install.stdout_lines }}"

- name: get the token for joining the worker nodes
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: print the kubernetes node join command
  debug:
    msg: "{{ kubernetes_join_command.stdout_lines }}"

- name: copy join command to local file.
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
