---
- name: logstash management
  hosts: sandbox
  become: true
  become_user: root
  roles:
  - {role: 'linux_logstash_stop_server'}
  - {role: 'linux_logstash_config_backup'}
  - {role: 'linux_logstash_start_server'}