---
- name: apply the flannel networking policy defintion
  shell: kubectl apply -f {{kubernetes_network_policy_repo}}

- name: get the token for joining the worker nodes
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: print the kubernetes node join command
  debug:
    msg: "{{ kubernetes_join_command.stdout_lines }}"

- name: copy join command to local file.
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
