---
- hosts: stack
  remote_user: admin
  become: true
  tasks:
  - name: Ensure HTTP package is installed
    yum: name=httpd state=present
  - name: Ensure HTTP service is enabled and running
    service: name=httpd state=started enabled=true
  - name: Enable http service in firewall
    firewalld: service=http permanent=yes state=enabled immediate=true
  - name: Copy html file to httpd docroot
    copy: 
      src: "{{ item }}"
      dest: /var/www/html/
    with_fileglob: "/home/admin/learnansible/apachehttpd/static/data-*" 
