---
- name: Configure kubectl
  hosts: fedkubemaster
  tasks:
  - name: Create a directory if it does not exist
    file:
      path: $HOME/.kube
      state: directory
      mode: '0755'
  - name: copies admin.conf to user's kube config
    become: true
    become_user: root
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/admin/.kube/config
      remote_src: yes
      owner: admin
      group: admin


