---
- name: Deploy flannel networking policy
  hosts: fedkubemaster
  tasks:
  - name: Apply the flannel networking policy defintion
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  - name: Get the token for joining the worker nodes
    shell: kubeadm token create  --print-join-command
    register: kubernetes_join_command
  - name: Print the kubernetes node join command
    debug:
      msg: "{{ kubernetes_join_command.stdout }}"
  - name: Copy join command to local file.
    local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
  
