---
- name: setup fedora build vm
  hosts: fedorabuild
  become: true
  become_user: root
  roles:
  - { role: "linux_ping", tags: "linux_ping" }
  - { role: "linux_install_packaging_tools", tags: "linux_install_packaging_tools" }
  - { role: "linux_kerberos_authetication", tags: "linux_kerberos_authetication" }
  - { role: "linux_package_gnuhello", tags: "linux_package_gnuhello", become: true, become_user: admin }







  