- name: "upload grafana config"
  template:
    src: "{{grafana_config_template}}"
    dest: "{{grafana_config_directory}}/grafana.ini"
    owner: "root"
    group: "grafana"
    mode: 0640

- name: "upload grafana prometheus datasource config yml"
  template:
    src: "{{grafana_datasource_template}}"
    dest: "{{grafana_config_directory}}/provisioning/datasources/{{grafana_datasource_template}}"
    owner: "root"
    group: "grafana"
    mode: 0640

- name: Update grafana semanage ports
  seport:
    ports: 3000,2121
    proto: tcp
    setype: grafana_port_t
    state: present
