- name: get system locale settings
  shell: localectl status
  register: locale_output

- name: print system locale settings
  debug: msg="{{ locale_output.stdout_lines }}"

- name: list available locales
  shell: localectl list-locales
  register: listlocale_output

- name: print list of system locales
  debug: msg="{{ listlocale_output.stdout_lines }}"

- name: list available keymaps
  shell: localectl list-keymaps
  register: listkeymaps_output

- name: print list of system keymaps
  debug: msg="{{ listkeymaps_output.stdout_lines }}"